=== api-evangelist/spoonacular/json-schema/spoonacular-ingredient-information-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "IngredientInformation",
  "description": "",
  "$id": "https://raw.githubusercontent.com/api-evangelist/spoonacular/refs/heads/main/json-schema/spoonacular-ingredient-information-schema.json",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer",
      "example": 716429
    },
    "original": {
      "type": "string",
      "minLength": 1,
      "example": "example"
    },
    "originalName": {
      "type": "string",
      "minLength": 1,
      "example": "Spaghetti"
    },
    "name": {
      "type": "string",
      "minLength": 1,
      "example": "Spaghetti"
    },
    "amount": {
      "type": "number",
      "example": 1
    },
    "unit": {
      "type": "string",
      "example": "metric"
    },
    "unitShort": {
      "type": "string",
      "example": "metric"
    },
    "unitLong": {
      "type": "string",
      "example": "metric"
    },
    "possibleUnits": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "estimatedCost": {
      "type": "object",
      "required": [
        "value",
        "unit"
      ],
      "properties": {
        "value": {
          "type": "number",
          "example": 1.0
        },
        "unit": {
          "type": "string",
          "minLength": 1,
          "example": "metric"
        }
      }
    },
    "consistency": {
      "type": "string",
      "minLength": 1,
      "example": "example"
    },
    "shoppingListUnits": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "aisle": {
      "type": "string",
      "minLength": 1,
      "example": "example"
    },
    "image": {
      "type": "string",
      "minLength": 1,
      "example": "example"
    },
    "meta": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "nutrition": {
      "type": "object",
      "required": [
        "nutrients",
        "properties",
        "caloricBreakdown",
        "weightPerServing"
      ],
      "properties": {
        "nutrients": {
          "type": "array",
          "uniqueItems": true,
          "minItems": 0,
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string",
                "minLength": 1
              },
              "amount": {
                "type": "number"
              },
              "unit": {
                "type": "string",
                "minLength": 1
              },
              "percentOfDailyNeeds": {
                "type": "number"
              }
            },
            "required": [
              "name",
              "amount",
              "unit",
              "percentOfDailyNeeds"
            ]
          }
        },
        "properties": {
          "type": "array",
          "uniqueItems": true,
          "minItems": 0,
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string",
                "minLength": 1
              },
              "amount": {
                "type": "number"
              },
              "unit": {
                "type": "string"
              }
            },
            "required": [
              "name",
              "amount",
              "unit"
            ]
          }
        },
        "caloricBreakdown": {
          "type": "object",
          "required": [
            "percentProtein",
            "percentFat",
            "percentCarbs"
          ],
          "properties": {
            "percentProtein": {
              "type": "number",
              "example": 1.0
            },
            "percentFat": {
              "type": "number",
              "example": 1.0
            },
            "percentCarbs": {
              "type": "number",
              "example": 1.0
            }
          }
        },
        "weightPerServing": {
          "type": "object",
          "required": [
            "amount",
            "unit"
          ],
          "properties": {
            "amount": {
              "type": "number",
              "example": 1
            },
            "unit": {
              "type": "string",
              "minLength": 1,
              "example": "metric"
            }
          }
        }
      }
    },
    "categoryPath": {
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  },
  "required": [
    "id",
    "original",
    "originalName",
    "name",
    "amount",
    "unit",
    "unitShort",
    "unitLong",
    "possibleUnits",
    "estimatedCost",
    "consistency",
    "aisle",
    "image",
    "meta"
  ],
  "example": {
    "id": 9266,
    "original": "pineapples",
    "originalName": "pineapples",
    "name": "pineapples",
    "amount": 1,
    "unit": "",
    "unitShort": "",
    "unitLong": "",
    "possibleUnits": [
      "piece",
      "slice",
      "fruit",
      "g",
      "oz",
      "cup",
      "serving"
    ],
    "estimatedCost": {
      "value": 299,
      "unit": "US Cents"
    },
    "consistency": "solid",
    "shoppingListUnits": [
      "pieces"
    ],
    "aisle": "Produce",
    "image": "pineapple.jpg",
    "meta": [],
    "nutrition": {
      "nutrients": [
        {
          "name": "Calories",
          "amount": 452.5,
          "unit": "cal",
          "percentOfDailyNeeds": 22.63
        },
        {
          "name": "Fat",
          "amount": 1.09,
          "unit": "g",
          "percentOfDailyNeeds": 1.67
        },
        {
          "name": "Saturated Fat",
          "amount": 0.08,
          "unit": "g",
          "percentOfDailyNeeds": 0.51
        },
        {
          "name": "Carbohydrates",
          "amount": 118.74,
          "unit": "g",
          "percentOfDailyNeeds": 39.58
        },
        {
          "name": "Net Carbohydrates",
          "amount": 106.07,
          "unit": "g",
          "percentOfDailyNeeds": 38.57
        },
        {
          "name": "Sugar",
          "amount": 89.14,
          "unit": "g",
          "percentOfDailyNeeds": 99.05
        },
        {
          "name": "Cholesterol",
          "amount": 0,
          "unit": "mg",
          "percentOfDailyNeeds": 0
        },
        {
          "name": "Sodium",
          "amount": 9.05,
          "unit": "mg",
          "percentOfDailyNeeds": 0.39
        },
        {
          "name": "Protein",
          "amount": 4.89,
          "unit": "g",
          "percentOfDailyNeeds": 9.77
        },
        {
          "name": "Vitamin C",
          "amount": 432.59,
          "unit": "mg",
          "percentOfDailyNeeds": 524.35
        },
        {
          "name": "Manganese",
          "amount": 8.39,
          "unit": "mg",
          "percentOfDailyNeeds": 419.47
        },
        {
          "name": "Fiber",
          "amount": 12.67,
          "unit": "g",
          "percentOfDailyNeeds": 50.68
        },
        {
          "name": "Vitamin B6",
          "amount": 1.01,
          "unit": "mg",
          "percentOfDailyNeeds": 50.68
        },
        {
          "name": "Copper",
          "amount": 1,
          "unit": "mg",
          "percentOfDailyNeeds": 49.78
        },
        {
          "name": "Vitamin B1",
          "amount": 0.72,
          "unit": "mg",
          "percentOfDailyNeeds": 47.66
        },
        {
          "name": "Folate",
          "amount": 162.9,
          "unit": "\u00b5g",
          "percentOfDailyNeeds": 40.73
        },
        {
          "name": "Potassium",
          "amount": 986.45,
          "unit": "mg",
          "percentOfDailyNeeds": 28.18
        },
        {
          "name": "Magnesium",
          "amount": 108.6,
          "unit": "mg",
          "percentOfDailyNeeds": 27.15
        },
        {
          "name": "Vitamin B3",
          "amount": 4.53,
          "unit": "mg",
          "percentOfDailyNeeds": 22.63
        },
        {
          "name": "Vitamin B5",
          "amount": 1.93,
          "unit": "mg",
          "percentOfDailyNeeds": 19.28
        },
        {
          "name": "Vitamin B2",
          "amount": 0.29,
          "unit": "mg",
          "percentOfDailyNeeds": 17.04
        },
        {
          "name": "Iron",
          "amount": 2.62,
          "unit": "mg",
          "percentOfDailyNeeds": 14.58
        },
        {
          "name": "Calcium",
          "amount": 117.65,
          "unit": "mg",
          "percentOfDailyNeeds": 11.77
        },
        {
          "name": "Vitamin A",
          "amount": 524.9,
          "unit": "IU",
          "percentOfDailyNeeds": 10.5
        },
        {
          "name": "Zinc",
          "amount": 1.09,
          "unit": "mg",
          "percentOfDailyNeeds": 7.24
        },
        {
          "name": "Phosphorus",
          "amount": 72.4,
          "unit": "mg",
          "percentOfDailyNeeds": 7.24
        },
        {
          "name": "Vitamin K",
          "amount": 6.34,
          "unit": "\u00b5g",
          "percentOfDailyNeeds": 6.03
        },
        {
          "name": "Selenium",
          "amount": 0.91,
          "unit": "\u00b5g",
          "percentOfDailyNeeds": 1.29
        },
        {
          "name": "Vitamin E",
          "amount": 0.18,
          "unit": "mg",
          "percentOfDailyNeeds": 1.21
        }
      ],
      "properties": [
        {
          "name": "Glycemic Index",
          "amount": 58.67,
          "unit": ""
        },
        {
          "name": "Glycemic Load",
          "amount": 62.23,
          "unit": ""
        }
      ],
      "caloricBreakdown": {
        "percentProtein": 3.88,
        "percentFat": 1.94,
        "percentCarbs": 94.18
      },
      "weightPerServing": {
        "amount": 905,
        "unit": "g"
      }
    },
    "categoryPath": [
      "tropical fruit",
      "fruit"
    ]
  }
}

=== api-evangelist/spoonacular/examples/spoonacular-ingredient-information-example.json
{
  "id": 9266,
  "original": "pineapples",
  "originalName": "pineapples",
  "name": "pineapples",
  "amount": 1,
  "unit": "",
  "unitShort": "",
  "unitLong": "",
  "possibleUnits": [
    "piece",
    "slice",
    "fruit",
    "g",
    "oz",
    "cup",
    "serving"
  ],
  "estimatedCost": {
    "value": 299,
    "unit": "US Cents"
  },
  "consistency": "solid",
  "shoppingListUnits": [
    "pieces"
  ],
  "aisle": "Produce",
  "image": "pineapple.jpg",
  "meta": [],
  "nutrition": {
    "nutrients": [
      {
        "name": "Calories",
        "amount": 452.5,
        "unit": "cal",
        "percentOfDailyNeeds": 22.63
      },
      {
        "name": "Fat",
        "amount": 1.09,
        "unit": "g",
        "percentOfDailyNeeds": 1.67
      },
      {
        "name": "Saturated Fat",
        "amount": 0.08,
        "unit": "g",
        "percentOfDailyNeeds": 0.51
      },
      {
        "name": "Carbohydrates",
        "amount": 118.74,
        "unit": "g",
        "percentOfDailyNeeds": 39.58
      },
      {
        "name": "Net Carbohydrates",
        "amount": 106.07,
        "unit": "g",
        "percentOfDailyNeeds": 38.57
      },
      {
        "name": "Sugar",
        "amount": 89.14,
        "unit": "g",
        "percentOfDailyNeeds": 99.05
      },
      {
        "name": "Cholesterol",
        "amount": 0,
        "unit": "mg",
        "percentOfDailyNeeds": 0
      },
      {
        "name": "Sodium",
        "amount": 9.05,
        "unit": "mg",
        "percentOfDailyNeeds": 0.39
      },
      {
        "name": "Protein",
        "amount": 4.89,
        "unit": "g",
        "percentOfDailyNeeds": 9.77
      },
      {
        "name": "Vitamin C",
        "amount": 432.59,
        "unit": "mg",
        "percentOfDailyNeeds": 524.35
      },
      {
        "name": "Manganese",
        "amount": 8.39,
        "unit": "mg",
        "percentOfDailyNeeds": 419.47
      },
      {
        "name": "Fiber",
        "amount": 12.67,
        "unit": "g",
        "percentOfDailyNeeds": 50.68
      },
      {
        "name": "Vitamin B6",
        "amount": 1.01,
        "unit": "mg",
        "percentOfDailyNeeds": 50.68
      },
      {
        "name": "Copper",
        "amount": 1,
        "unit": "mg",
        "percentOfDailyNeeds": 49.78
      },
      {
        "name": "Vitamin B1",
        "amount": 0.72,
        "unit": "mg",
        "percentOfDailyNeeds": 47.66
      },
      {
        "name": "Folate",
        "amount": 162.9,
        "unit": "\u00b5g",
        "percentOfDailyNeeds": 40.73
      },
      {
        "name": "Potassium",
        "amount": 986.45,
        "unit": "mg",
        "percentOfDailyNeeds": 28.18
      },
      {
        "name": "Magnesium",
        "amount": 108.6,
        "unit": "mg",
        "percentOfDailyNeeds": 27.15
      },
      {
        "name": "Vitamin B3",
        "amount": 4.53,
        "unit": "mg",
        "percentOfDailyNeeds": 22.63
      },
      {
        "name": "Vitamin B5",
        "amount": 1.93,
        "unit": "mg",
        "percentOfDailyNeeds": 19.28
      },
      {
        "name": "Vitamin B2",
        "amount": 0.29,
        "unit": "mg",
        "percentOfDailyNeeds": 17.04
      },
      {
        "name": "Iron",
        "amount": 2.62,
        "unit": "mg",
        "percentOfDailyNeeds": 14.58
      },
      {
        "name": "Calcium",
        "amount": 117.65,
        "unit": "mg",
        "percentOfDailyNeeds": 11.77
      },
      {
        "name": "Vitamin A",
        "amount": 524.9,
        "unit": "IU",
        "percentOfDailyNeeds": 10.5
      },
      {
        "name": "Zinc",
        "amount": 1.09,
        "unit": "mg",
        "percentOfDailyNeeds": 7.24
      },
      {
        "name": "Phosphorus",
        "amount": 72.4,
        "unit": "mg",
        "percentOfDailyNeeds": 7.24
      },
      {
        "name": "Vitamin K",
        "amount": 6.34,
        "unit": "\u00b5g",
        "percentOfDailyNeeds": 6.03
      },
      {
        "name": "Selenium",
        "amount": 0.91,
        "unit": "\u00b5g",
        "percentOfDailyNeeds": 1.29
      },
      {
        "name": "Vitamin E",
        "amount": 0.18,
        "unit": "mg",
        "percentOfDailyNeeds": 1.21
      }
    ],
    "properties": [
      {
        "name": "Glycemic Index",
        "amount": 58.67,
        "unit": ""
      },
      {
        "name": "Glycemic Load",
        "amount": 62.23,
        "unit": ""
      }
    ],
    "caloricBreakdown": {
      "percentProtein": 3.88,
      "percentFat": 1.94,
      "percentCarbs": 94.18
    },
    "weightPerServing": {
      "amount": 905,
      "unit": "g"
    }
  },
  "categoryPath": [
    "tropical fruit",
    "fruit"
  ]
}
