=== api-evangelist/spoonacular/json-schema/spoonacular-recipe-information-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "RecipeInformation",
  "description": "",
  "$id": "https://raw.githubusercontent.com/api-evangelist/spoonacular/refs/heads/main/json-schema/spoonacular-recipe-information-schema.json",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer",
      "example": 716429
    },
    "title": {
      "type": "string",
      "minLength": 1,
      "example": "example"
    },
    "image": {
      "type": "string",
      "nullable": true,
      "example": "example"
    },
    "imageType": {
      "type": "string",
      "minLength": 1,
      "example": "example"
    },
    "servings": {
      "type": "number",
      "example": 1.0
    },
    "readyInMinutes": {
      "type": "integer",
      "example": 1
    },
    "preparationMinutes": {
      "type": "integer",
      "nullable": true,
      "example": 1
    },
    "cookingMinutes": {
      "type": "integer",
      "nullable": true,
      "example": 1
    },
    "license": {
      "type": "string",
      "minLength": 1,
      "example": "example"
    },
    "sourceName": {
      "type": "string",
      "minLength": 1,
      "example": "Spaghetti"
    },
    "sourceUrl": {
      "type": "string",
      "minLength": 1,
      "example": "https://example.com"
    },
    "spoonacularSourceUrl": {
      "type": "string",
      "example": "https://example.com"
    },
    "aggregateLikes": {
      "type": "integer",
      "example": 1
    },
    "healthScore": {
      "type": "number",
      "example": 1.0
    },
    "spoonacularScore": {
      "type": "number",
      "example": 1.0
    },
    "pricePerServing": {
      "type": "number",
      "example": 1.0
    },
    "analyzedInstructions": {
      "type": "array",
      "items": {
        "type": "object"
      }
    },
    "cheap": {
      "type": "boolean",
      "example": false
    },
    "creditsText": {
      "type": "string",
      "minLength": 1,
      "example": "example"
    },
    "cuisines": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dairyFree": {
      "type": "boolean",
      "example": false
    },
    "diets": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "gaps": {
      "type": "string",
      "minLength": 1,
      "example": "example"
    },
    "glutenFree": {
      "type": "boolean",
      "example": false
    },
    "instructions": {
      "type": "string",
      "nullable": true,
      "example": "example"
    },
    "lowFodmap": {
      "type": "boolean",
      "example": false
    },
    "occasions": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "sustainable": {
      "type": "boolean",
      "example": false
    },
    "vegan": {
      "type": "boolean",
      "example": false
    },
    "vegetarian": {
      "type": "boolean",
      "example": false
    },
    "veryHealthy": {
      "type": "boolean",
      "example": false
    },
    "veryPopular": {
      "type": "boolean",
      "example": false
    },
    "weightWatcherSmartPoints": {
      "type": "number",
      "example": 1.0
    },
    "dishTypes": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "extendedIngredients": {
      "type": "array",
      "uniqueItems": true,
      "minItems": 0,
      "items": {
        "type": "object",
        "properties": {
          "aisle": {
            "type": "string",
            "minLength": 1
          },
          "amount": {
            "type": "number"
          },
          "consistency": {
            "type": "string",
            "minLength": 1
          },
          "id": {
            "type": "integer"
          },
          "image": {
            "type": "string",
            "minLength": 1
          },
          "measures": {
            "type": "object",
            "properties": {
              "metric": {
                "type": "object",
                "required": [
                  "amount",
                  "unitLong",
                  "unitShort"
                ],
                "properties": {
                  "amount": {
                    "type": "number"
                  },
                  "unitLong": {
                    "type": "string",
                    "minLength": 0
                  },
                  "unitShort": {
                    "type": "string",
                    "minLength": 0
                  }
                }
              },
              "us": {
                "type": "object",
                "required": [
                  "amount",
                  "unitLong",
                  "unitShort"
                ],
                "properties": {
                  "amount": {
                    "type": "number"
                  },
                  "unitLong": {
                    "type": "string",
                    "minLength": 0
                  },
                  "unitShort": {
                    "type": "string",
                    "minLength": 0
                  }
                }
              }
            },
            "required": [
              "metric",
              "us"
            ]
          },
          "meta": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "name": {
            "type": "string",
            "minLength": 1
          },
          "original": {
            "type": "string",
            "minLength": 1
          },
          "originalName": {
            "type": "string",
            "minLength": 1
          },
          "unit": {
            "type": "string",
            "minLength": 0
          }
        },
        "required": [
          "aisle",
          "amount",
          "consistency",
          "id",
          "image",
          "name",
          "original",
          "originalName",
          "unit"
        ]
      }
    },
    "summary": {
      "type": "string",
      "minLength": 1,
      "example": "example"
    },
    "winePairing": {
      "type": "object",
      "properties": {
        "pairedWines": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "pairingText": {
          "type": "string",
          "minLength": 1,
          "example": "example"
        },
        "productMatches": {
          "type": "array",
          "uniqueItems": true,
          "minItems": 0,
          "items": {
            "type": "object",
            "properties": {
              "id": {
                "type": "integer"
              },
              "title": {
                "type": "string",
                "minLength": 1
              },
              "description": {
                "type": "string",
                "minLength": 1
              },
              "price": {
                "type": "string",
                "minLength": 1
              },
              "imageUrl": {
                "type": "string",
                "minLength": 1
              },
              "averageRating": {
                "type": "number"
              },
              "ratingCount": {
                "type": "integer"
              },
              "score": {
                "type": "number"
              },
              "link": {
                "type": "string",
                "minLength": 1
              }
            },
            "required": [
              "id",
              "title",
              "description",
              "price",
              "imageUrl",
              "averageRating",
              "ratingCount",
              "score",
              "link"
            ]
          }
        }
      }
    },
    "taste": {
      "$ref": "#/components/schemas/TasteInformation"
    }
  },
  "required": [
    "id",
    "title",
    "image",
    "servings",
    "readyInMinutes",
    "sourceName",
    "sourceUrl",
    "spoonacularSourceUrl",
    "aggregateLikes",
    "healthScore",
    "spoonacularScore",
    "pricePerServing",
    "analyzedInstructions",
    "cheap",
    "creditsText",
    "cuisines",
    "dairyFree",
    "diets",
    "gaps",
    "glutenFree",
    "instructions",
    "lowFodmap",
    "occasions",
    "sustainable",
    "vegan",
    "vegetarian",
    "veryHealthy",
    "veryPopular",
    "weightWatcherSmartPoints",
    "dishTypes",
    "extendedIngredients",
    "summary"
  ],
  "example": {
    "id": 716429,
    "title": "Pasta with Garlic, Scallions, Cauliflower & Breadcrumbs",
    "image": "https://spoonacular.com/recipeImages/716429-556x370.jpg",
    "imageType": "jpg",
    "servings": 2,
    "readyInMinutes": 45,
    "license": "CC BY-SA 3.0",
    "sourceName": "Full Belly Sisters",
    "sourceUrl": "http://fullbellysisters.blogspot.com/2012/06/pasta-with-garlic-scallions-cauliflower.html",
    "spoonacularSourceUrl": "https://spoonacular.com/pasta-with-garlic-scallions-cauliflower-breadcrumbs-716429",
    "aggregateLikes": 209,
    "healthScore": 19,
    "spoonacularScore": 83,
    "pricePerServing": 163.15,
    "analyzedInstructions": [],
    "cheap": false,
    "creditsText": "Full Belly Sisters",
    "cuisines": [],
    "dairyFree": false,
    "diets": [],
    "gaps": "no",
    "glutenFree": false,
    "instructions": "",
    "lowFodmap": false,
    "occasions": [],
    "sustainable": false,
    "vegan": false,
    "vegetarian": false,
    "veryHealthy": false,
    "veryPopular": false,
    "weightWatcherSmartPoints": 17,
    "dishTypes": [
      "lunch",
      "main course",
      "main dish",
      "dinner"
    ],
    "extendedIngredients": [
      {
        "aisle": "Milk, Eggs, Other Dairy",
        "amount": 1,
        "consistency": "solid",
        "id": 1001,
        "image": "butter-sliced.jpg",
        "measures": {
          "metric": {
            "amount": 1,
            "unitLong": "Tbsp",
            "unitShort": "Tbsp"
          },
          "us": {
            "amount": 1,
            "unitLong": "Tbsp",
            "unitShort": "Tbsp"
          }
        },
        "meta": [],
        "name": "butter",
        "original": "1 tbsp butter",
        "originalName": "butter",
        "unit": "tbsp"
      },
      {
        "aisle": "Produce",
        "amount": 2,
        "consistency": "solid",
        "id": 10011135,
        "image": "cauliflower.jpg",
        "measures": {
          "metric": {
            "amount": 473.176,
            "unitLong": "milliliters",
            "unitShort": "ml"
          },
          "us": {
            "amount": 2,
            "unitLong": "cups",
            "unitShort": "cups"
          }
        },
        "meta": [
          "frozen",
          "thawed",
          "cut into bite-sized pieces"
        ],
        "name": "cauliflower florets",
        "original": "about 2 cups frozen cauliflower florets, thawed, cut into bite-sized pieces",
        "originalName": "about frozen cauliflower florets, thawed, cut into bite-sized pieces",
        "unit": "cups"
      },
      {
        "aisle": "Cheese",
        "amount": 2,
        "consistency": "solid",
        "id": 1041009,
        "image": "cheddar-cheese.png",
        "measures": {
          "metric": {
            "amount": 2,
            "unitLong": "Tbsps",
            "unitShort": "Tbsps"
          },
          "us": {
            "amount": 2,
            "unitLong": "Tbsps",
            "unitShort": "Tbsps"
          }
        },
        "meta": [
          "grated",
          "(I used romano)"
        ],
        "name": "cheese",
        "original": "2 tbsp grated cheese (I used romano)",
        "originalName": "grated cheese (I used romano)",
        "unit": "tbsp"
      },
      {
        "aisle": "Oil, Vinegar, Salad Dressing",
        "amount": 1,
        "consistency": "liquid",
        "id": 1034053,
        "image": "olive-oil.jpg",
        "measures": {
          "metric": {
            "amount": 1,
            "unitLong": "Tbsp",
            "unitShort": "Tbsp"
          },
          "us": {
            "amount": 1,
            "unitLong": "Tbsp",
            "unitShort": "Tbsp"
          }
        },
        "meta": [],
        "name": "extra virgin olive oil",
        "original": "1-2 tbsp extra virgin olive oil",
        "originalName": "extra virgin olive oil",
        "unit": "tbsp"
      },
      {
        "aisle": "Produce",
        "amount": 5,
        "consistency": "solid",
        "id": 11215,
        "image": "garlic.jpg",
        "measures": {
          "metric": {
            "amount": 5,
            "unitLong": "cloves",
            "unitShort": "cloves"
          },
          "us": {
            "amount": 5,
            "unitLong": "cloves",
            "unitShort": "cloves"
          }
        },
        "meta": [],
        "name": "garlic",
        "original": "5-6 cloves garlic",
        "originalName": "garlic",
        "unit": "cloves"
      },
      {
        "aisle": "Pasta and Rice",
        "amount": 6,
        "consistency": "solid",
        "id": 20420,
        "image": "fusilli.jpg",
        "measures": {
          "metric": {
            "amount": 170.097,
            "unitLong": "grams",
            "unitShort": "g"
          },
          "us": {
            "amount": 6,
            "unitLong": "ounces",
            "unitShort": "oz"
          }
        },
        "meta": [
          "(I used linguine)"
        ],
        "name": "pasta",
        "original": "6-8 ounces pasta (I used linguine)",
        "originalName": "pasta (I used linguine)",
        "unit": "ounces"
      },
      {
        "aisle": "Spices and Seasonings",
        "amount": 2,
        "consistency": "solid",
        "id": 1032009,
        "image": "red-pepper-flakes.jpg",
        "measures": {
          "metric": {
            "amount": 2,
            "unitLong": "pinches",
            "unitShort": "pinches"
          },
          "us": {
            "amount": 2,
            "unitLong": "pinches",
            "unitShort": "pinches"
          }
        },
        "meta": [
          "red"
        ],
        "name": "red pepper flakes",
        "original": "couple of pinches red pepper flakes, optional",
        "originalName": "couple of red pepper flakes, optional",
        "unit": "pinches"
      },
      {
        "aisle": "Spices and Seasonings",
        "amount": 2,
        "consistency": "solid",
        "id": 1102047,
        "image": "salt-and-pepper.jpg",
        "measures": {
          "metric": {
            "amount": 2,
            "unitLong": "servings",
            "unitShort": "servings"
          },
          "us": {
            "amount": 2,
            "unitLong": "servings",
            "unitShort": "servings"
          }
        },
        "meta": [
          "to taste"
        ],
        "name": "salt and pepper",
        "original": "salt and pepper, to taste",
        "originalName": "salt and pepper, to taste",
        "unit": "servings"
      },
      {
        "aisle": "Produce",
        "amount": 3,
        "consistency": "solid",
        "id": 11291,
        "image": "spring-onions.jpg",
        "measures": {
          "metric": {
            "amount": 3,
            "unitLong": "",
            "unitShort": ""
          },
          "us": {
            "amount": 3,
            "unitLong": "",
            "unitShort": ""
          }
        },
        "meta": [
          "white",
          "green",
          "separated",
          "chopped"
        ],
        "name": "scallions",
        "original": "3 scallions, chopped, white and green parts separated",
        "originalName": "scallions, chopped, white and green parts separated",
        "unit": ""
      },
      {
        "aisle": "Alcoholic Beverages",
        "amount": 2,
        "consistency": "liquid",
        "id": 14106,
        "image": "white-wine.jpg",
        "measures": {
          "metric": {
            "amount": 2,
            "unitLong": "Tbsps",
            "unitShort": "Tbsps"
          },
          "us": {
            "amount": 2,
            "unitLong": "Tbsps",
            "unitShort": "Tbsps"
          }
        },
        "meta": [
          "white"
        ],
        "name": "white wine",
        "original": "2-3 tbsp white wine",
        "originalName": "white wine",
        "unit": "tbsp"
      },
      {
        "aisle": "Pasta and Rice",
        "amount": 0.25,
        "consistency": "solid",
        "id": 99025,
        "image": "breadcrumbs.jpg",
        "measures": {
          "metric": {
            "amount": 59.147,
            "unitLong": "milliliters",
            "unitShort": "ml"
          },
          "us": {
            "amount": 0.25,
            "unitLong": "cups",
            "unitShort": "cups"
          }
        },
        "meta": [
          "whole wheat",
          "(I used panko)"
        ],
        "name": "whole wheat bread crumbs",
        "original": "1/4 cup whole wheat bread crumbs (I used panko)",
        "originalName": "whole wheat bread crumbs (I used panko)",
        "unit": "cup"
      }
    ],
    "summary": "Pasta with Garlic, Scallions, Cauliflower & Breadcrumbs might be a good recipe to expand your main course repertoire. One portion of this dish contains approximately &lt;b&gt;19g of protein &lt;/b&gt;,  &lt;b&gt;20g of fat &lt;/b&gt;, and a total of  &lt;b&gt;584 calories &lt;/b&gt;. For  &lt;b&gt;$1.63 per serving &lt;/b&gt;, this recipe  &lt;b&gt;covers 23% &lt;/b&gt; of your daily requirements of vitamins and minerals. This recipe serves 2. It is brought to you by fullbellysisters.blogspot.com. 209 people were glad they tried this recipe. A mixture of scallions, salt and pepper, white wine, and a handful of other ingredients are all it takes to make this recipe so scrumptious. From preparation to the plate, this recipe takes approximately  &lt;b&gt;45 minutes &lt;/b&gt;. All things considered, we decided this recipe  &lt;b&gt;deserves a spoonacular score of 83% &lt;/b&gt;. This score is awesome. If you like this recipe, take a look at these similar recipes: &lt;a href=\"https://spoonacular.com/recipes/cauliflower-gratin-with-garlic-breadcrumbs-318375\">Cauliflower Gratin with Garlic Breadcrumbs&lt;/a&gt;, &lt; href=\"https://spoonacular.com/recipes/pasta-with-cauliflower-sausage-breadcrumbs-30437\">Pasta With Cauliflower, Sausage, & Breadcrumbs&lt;/a&gt;, and &lt;a href=\"https://spoonacular.com/recipes/pasta-with-roasted-cauliflower-parsley-and-breadcrumbs-30738\">Pasta With Roasted Cauliflower, Parsley, And Breadcrumbs&lt;/a&gt;.",
    "winePairing": {
      "pairedWines": [
        "chardonnay",
        "gruener veltliner",
        "sauvignon blanc"
      ],
      "pairingText": "Chardonnay, Gruener Veltliner, and Sauvignon Blanc are great choices for Pasta. Sauvignon Blanc and Gruner Veltliner both have herby notes that complement salads with enough acid to match tart vinaigrettes, while a Chardonnay can be a good pick for creamy salad dressings. The Buddha Kat Winery Chardonnay with a 4 out of 5 star rating seems like a good match. It costs about 25 dollars per bottle.",
      "productMatches": [
        {
          "id": 469199,
          "title": "Buddha Kat Winery Chardonnay",
          "description": "We barrel ferment our Chardonnay and age it in a mix of Oak and Stainless. Giving this light bodied wine modest oak character, a delicate floral aroma, and a warming finish.",
          "price": "$25.0",
          "imageUrl": "https://spoonacular.com/productImages/469199-312x231.jpg",
          "averageRating": 0.8,
          "ratingCount": 1,
          "score": 0.55,
          "link": "https://www.amazon.com/2015-Buddha-Kat-Winery-Chardonnay/dp/B00OSAVVM4?tag=spoonacular-20"
        }
      ]
    }
  }
}

=== api-evangelist/spoonacular/examples/spoonacular-recipe-information-example.json
{
  "id": 716429,
  "title": "Pasta with Garlic, Scallions, Cauliflower & Breadcrumbs",
  "image": "https://spoonacular.com/recipeImages/716429-556x370.jpg",
  "imageType": "jpg",
  "servings": 2,
  "readyInMinutes": 45,
  "license": "CC BY-SA 3.0",
  "sourceName": "Full Belly Sisters",
  "sourceUrl": "http://fullbellysisters.blogspot.com/2012/06/pasta-with-garlic-scallions-cauliflower.html",
  "spoonacularSourceUrl": "https://spoonacular.com/pasta-with-garlic-scallions-cauliflower-breadcrumbs-716429",
  "aggregateLikes": 209,
  "healthScore": 19,
  "spoonacularScore": 83,
  "pricePerServing": 163.15,
  "analyzedInstructions": [],
  "cheap": false,
  "creditsText": "Full Belly Sisters",
  "cuisines": [],
  "dairyFree": false,
  "diets": [],
  "gaps": "no",
  "glutenFree": false,
  "instructions": "",
  "lowFodmap": false,
  "occasions": [],
  "sustainable": false,
  "vegan": false,
  "vegetarian": false,
  "veryHealthy": false,
  "veryPopular": false,
  "weightWatcherSmartPoints": 17,
  "dishTypes": [
    "lunch",
    "main course",
    "main dish",
    "dinner"
  ],
  "extendedIngredients": [
    {
      "aisle": "Milk, Eggs, Other Dairy",
      "amount": 1,
      "consistency": "solid",
      "id": 1001,
      "image": "butter-sliced.jpg",
      "measures": {
        "metric": {
          "amount": 1,
          "unitLong": "Tbsp",
          "unitShort": "Tbsp"
        },
        "us": {
          "amount": 1,
          "unitLong": "Tbsp",
          "unitShort": "Tbsp"
        }
      },
      "meta": [],
      "name": "butter",
      "original": "1 tbsp butter",
      "originalName": "butter",
      "unit": "tbsp"
    },
    {
      "aisle": "Produce",
      "amount": 2,
      "consistency": "solid",
      "id": 10011135,
      "image": "cauliflower.jpg",
      "measures": {
        "metric": {
          "amount": 473.176,
          "unitLong": "milliliters",
          "unitShort": "ml"
        },
        "us": {
          "amount": 2,
          "unitLong": "cups",
          "unitShort": "cups"
        }
      },
      "meta": [
        "frozen",
        "thawed",
        "cut into bite-sized pieces"
      ],
      "name": "cauliflower florets",
      "original": "about 2 cups frozen cauliflower florets, thawed, cut into bite-sized pieces",
      "originalName": "about frozen cauliflower florets, thawed, cut into bite-sized pieces",
      "unit": "cups"
    },
    {
      "aisle": "Cheese",
      "amount": 2,
      "consistency": "solid",
      "id": 1041009,
      "image": "cheddar-cheese.png",
      "measures": {
        "metric": {
          "amount": 2,
          "unitLong": "Tbsps",
          "unitShort": "Tbsps"
        },
        "us": {
          "amount": 2,
          "unitLong": "Tbsps",
          "unitShort": "Tbsps"
        }
      },
      "meta": [
        "grated",
        "(I used romano)"
      ],
      "name": "cheese",
      "original": "2 tbsp grated cheese (I used romano)",
      "originalName": "grated cheese (I used romano)",
      "unit": "tbsp"
    },
    {
      "aisle": "Oil, Vinegar, Salad Dressing",
      "amount": 1,
      "consistency": "liquid",
      "id": 1034053,
      "image": "olive-oil.jpg",
      "measures": {
        "metric": {
          "amount": 1,
          "unitLong": "Tbsp",
          "unitShort": "Tbsp"
        },
        "us": {
          "amount": 1,
          "unitLong": "Tbsp",
          "unitShort": "Tbsp"
        }
      },
      "meta": [],
      "name": "extra virgin olive oil",
      "original": "1-2 tbsp extra virgin olive oil",
      "originalName": "extra virgin olive oil",
      "unit": "tbsp"
    },
    {
      "aisle": "Produce",
      "amount": 5,
      "consistency": "solid",
      "id": 11215,
      "image": "garlic.jpg",
      "measures": {
        "metric": {
          "amount": 5,
          "unitLong": "cloves",
          "unitShort": "cloves"
        },
        "us": {
          "amount": 5,
          "unitLong": "cloves",
          "unitShort": "cloves"
        }
      },
      "meta": [],
      "name": "garlic",
      "original": "5-6 cloves garlic",
      "originalName": "garlic",
      "unit": "cloves"
    },
    {
      "aisle": "Pasta and Rice",
      "amount": 6,
      "consistency": "solid",
      "id": 20420,
      "image": "fusilli.jpg",
      "measures": {
        "metric": {
          "amount": 170.097,
          "unitLong": "grams",
          "unitShort": "g"
        },
        "us": {
          "amount": 6,
          "unitLong": "ounces",
          "unitShort": "oz"
        }
      },
      "meta": [
        "(I used linguine)"
      ],
      "name": "pasta",
      "original": "6-8 ounces pasta (I used linguine)",
      "originalName": "pasta (I used linguine)",
      "unit": "ounces"
    },
    {
      "aisle": "Spices and Seasonings",
      "amount": 2,
      "consistency": "solid",
      "id": 1032009,
      "image": "red-pepper-flakes.jpg",
      "measures": {
        "metric": {
          "amount": 2,
          "unitLong": "pinches",
          "unitShort": "pinches"
        },
        "us": {
          "amount": 2,
          "unitLong": "pinches",
          "unitShort": "pinches"
        }
      },
      "meta": [
        "red"
      ],
      "name": "red pepper flakes",
      "original": "couple of pinches red pepper flakes, optional",
      "originalName": "couple of red pepper flakes, optional",
      "unit": "pinches"
    },
    {
      "aisle": "Spices and Seasonings",
      "amount": 2,
      "consistency": "solid",
      "id": 1102047,
      "image": "salt-and-pepper.jpg",
      "measures": {
        "metric": {
          "amount": 2,
          "unitLong": "servings",
          "unitShort": "servings"
        },
        "us": {
          "amount": 2,
          "unitLong": "servings",
          "unitShort": "servings"
        }
      },
      "meta": [
        "to taste"
      ],
      "name": "salt and pepper",
      "original": "salt and pepper, to taste",
      "originalName": "salt and pepper, to taste",
      "unit": "servings"
    },
    {
      "aisle": "Produce",
      "amount": 3,
      "consistency": "solid",
      "id": 11291,
      "image": "spring-onions.jpg",
      "measures": {
        "metric": {
          "amount": 3,
          "unitLong": "",
          "unitShort": ""
        },
        "us": {
          "amount": 3,
          "unitLong": "",
          "unitShort": ""
        }
      },
      "meta": [
        "white",
        "green",
        "separated",
        "chopped"
      ],
      "name": "scallions",
      "original": "3 scallions, chopped, white and green parts separated",
      "originalName": "scallions, chopped, white and green parts separated",
      "unit": ""
    },
    {
      "aisle": "Alcoholic Beverages",
      "amount": 2,
      "consistency": "liquid",
      "id": 14106,
      "image": "white-wine.jpg",
      "measures": {
        "metric": {
          "amount": 2,
          "unitLong": "Tbsps",
          "unitShort": "Tbsps"
        },
        "us": {
          "amount": 2,
          "unitLong": "Tbsps",
          "unitShort": "Tbsps"
        }
      },
      "meta": [
        "white"
      ],
      "name": "white wine",
      "original": "2-3 tbsp white wine",
      "originalName": "white wine",
      "unit": "tbsp"
    },
    {
      "aisle": "Pasta and Rice",
      "amount": 0.25,
      "consistency": "solid",
      "id": 99025,
      "image": "breadcrumbs.jpg",
      "measures": {
        "metric": {
          "amount": 59.147,
          "unitLong": "milliliters",
          "unitShort": "ml"
        },
        "us": {
          "amount": 0.25,
          "unitLong": "cups",
          "unitShort": "cups"
        }
      },
      "meta": [
        "whole wheat",
        "(I used panko)"
      ],
      "name": "whole wheat bread crumbs",
      "original": "1/4 cup whole wheat bread crumbs (I used panko)",
      "originalName": "whole wheat bread crumbs (I used panko)",
      "unit": "cup"
    }
  ],
  "summary": "Pasta with Garlic, Scallions, Cauliflower & Breadcrumbs might be a good recipe to expand your main course repertoire. One portion of this dish contains approximately &lt;b&gt;19g of protein &lt;/b&gt;,  &lt;b&gt;20g of fat &lt;/b&gt;, and a total of  &lt;b&gt;584 calories &lt;/b&gt;. For  &lt;b&gt;$1.63 per serving &lt;/b&gt;, this recipe  &lt;b&gt;covers 23% &lt;/b&gt; of your daily requirements of vitamins and minerals. This recipe serves 2. It is brought to you by fullbellysisters.blogspot.com. 209 people were glad they tried this recipe. A mixture of scallions, salt and pepper, white wine, and a handful of other ingredients are all it takes to make this recipe so scrumptious. From preparation to the plate, this recipe takes approximately  &lt;b&gt;45 minutes &lt;/b&gt;. All things considered, we decided this recipe  &lt;b&gt;deserves a spoonacular score of 83% &lt;/b&gt;. This score is awesome. If you like this recipe, take a look at these similar recipes: &lt;a href=\"https://spoonacular.com/recipes/cauliflower-gratin-with-garlic-breadcrumbs-318375\">Cauliflower Gratin with Garlic Breadcrumbs&lt;/a&gt;, &lt; href=\"https://spoonacular.com/recipes/pasta-with-cauliflower-sausage-breadcrumbs-30437\">Pasta With Cauliflower, Sausage, & Breadcrumbs&lt;/a&gt;, and &lt;a href=\"https://spoonacular.com/recipes/pasta-with-roasted-cauliflower-parsley-and-breadcrumbs-30738\">Pasta With Roasted Cauliflower, Parsley, And Breadcrumbs&lt;/a&gt;.",
  "winePairing": {
    "pairedWines": [
      "chardonnay",
      "gruener veltliner",
      "sauvignon blanc"
    ],
    "pairingText": "Chardonnay, Gruener Veltliner, and Sauvignon Blanc are great choices for Pasta. Sauvignon Blanc and Gruner Veltliner both have herby notes that complement salads with enough acid to match tart vinaigrettes, while a Chardonnay can be a good pick for creamy salad dressings. The Buddha Kat Winery Chardonnay with a 4 out of 5 star rating seems like a good match. It costs about 25 dollars per bottle.",
